{% set name = "scipy-sugar" %}
{% set version = "1.0.9" %}
{% set sha256 = "d88d723afbcdcbec81996d2f8723b980d7a43fecf5da3d05ece5c10bfa32fcf1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pytest-runner
    - setuptools >=37.0.0
    - pypandoc
    - wheel
    - pip
  run:
    - python
    - numpy
    - scipy
    - pytest-doctestplus

test:
  requires:
    - pytest >=3
    - pytest-doctestplus
  imports:
    - scipy_sugar
  commands:
    - python -c "import sys; import scipy_sugar; sys.exit(scipy_sugar.test())"

about:
  home: https://github.com/limix/scipy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Missing SciPy functionalities'
  doc_url: https://scipy-sugar.readthedocs.io/
  dev_url: https://github.com/limix/scipy-sugar

extra:
  recipe-maintainers:
    - Horta
