{% set name = "scipy-sugar" %}
{% set version = "1.0.2" %}
{% set sha256 = "2942681512256c40bc7801a38701b12b5dff413dd6c4d04aafd1ee79d36529b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

test:
  requires:
    - pytest >=3
  imports:
    - scipy_sugar
  commands:
    - python -c "import sys; import scipy_sugar; sys.exit(scipy_sugar.test())"

about:
  home: https://github.com/limix/scipy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Missing SciPy functionalities'
  doc_url: https://scipy-sugar.readthedocs.io/
  dev_url: https://github.com/limix/scipy-sugar

extra:
  recipe-maintainers:
    - Horta
