# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UQs9qNZzSXYQSahdXVUNMWxwZE/uzgJp6q47Zo3eUG+YChLeAId6AiShmUcIwxpux4y9KVxUEjigLMnXha+mg9o+VaK0TAFLGQ8zt7Foj3PSgYXebt8rbDcHmuWfXZ7sIw6TSI+AH0ZM0UtAycfwB9rhi5WMYEpIdjS63rbfS59cnoMAIyrj2GVj869aih5/LtmMVuBD6T7Dp3gLtVlSPGPJ9LIlbsM11w4ROqnmTUfKzwAKtvuLLgEKJ6RRQ5OO5FipYaXhEm8q9mUhsvzMeyhlfUDTkui0Af45vnPs/HV3qHuqK6DTVLnmrEskeOxg/kxfW/S/hDsa2vCKgxPAba8bAnNYbecPiJd+XZ8ev5mBNkPyaxMKfv1+kZpIOPMgcpd81/Ye6KMQGyL5syi+vwUvwxJ2sWqygdTHpC//tDW/Ebc7pGDj4+oUde7LNpgPKcOJeCj6DfsupYgwV4PKXwkoh9HdIeI4T6QmAi60Q7HzlHAiCEVJEW8Z6Ye43iXStPAiNO7Xx6AZuNHE2/jr7F0sbPj+vWxDiCOvs/UjK49nSfPkyTBCENu2IezE0k+Bd0I1HcR2+7XLAafCeHU61W6A6yMvBKG56BgYe3zZLml0fODYcXSfbMJP9hbh/Ch/oZ93O4CwZU9MjYSp72QuriWcK4b/aFiBepk/5j9yvx0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
