travis:
  secure:
    BINSTAR_TOKEN: UQs9qNZzSXYQSahdXVUNMWxwZE/uzgJp6q47Zo3eUG+YChLeAId6AiShmUcIwxpux4y9KVxUEjigLMnXha+mg9o+VaK0TAFLGQ8zt7Foj3PSgYXebt8rbDcHmuWfXZ7sIw6TSI+AH0ZM0UtAycfwB9rhi5WMYEpIdjS63rbfS59cnoMAIyrj2GVj869aih5/LtmMVuBD6T7Dp3gLtVlSPGPJ9LIlbsM11w4ROqnmTUfKzwAKtvuLLgEKJ6RRQ5OO5FipYaXhEm8q9mUhsvzMeyhlfUDTkui0Af45vnPs/HV3qHuqK6DTVLnmrEskeOxg/kxfW/S/hDsa2vCKgxPAba8bAnNYbecPiJd+XZ8ev5mBNkPyaxMKfv1+kZpIOPMgcpd81/Ye6KMQGyL5syi+vwUvwxJ2sWqygdTHpC//tDW/Ebc7pGDj4+oUde7LNpgPKcOJeCj6DfsupYgwV4PKXwkoh9HdIeI4T6QmAi60Q7HzlHAiCEVJEW8Z6Ye43iXStPAiNO7Xx6AZuNHE2/jr7F0sbPj+vWxDiCOvs/UjK49nSfPkyTBCENu2IezE0k+Bd0I1HcR2+7XLAafCeHU61W6A6yMvBKG56BgYe3zZLml0fODYcXSfbMJP9hbh/Ch/oZ93O4CwZU9MjYSp72QuriWcK4b/aFiBepk/5j9yvx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
