travis:
  secure:
    BINSTAR_TOKEN: qrGJwsiByFa/YBPJvPhPgojgU8aZSoEqn7L1sduXrohp+FsvHAovfDVZLnu1P9N8qUIYt71aDg2uKFLJHsGDSES1x/+qIM1BIZnPHP9H0O0xpYATM3tkWnmgYnQ1O2GlyiuIvnK3frQTah7dq3k0Kdw8cpjBbjHFK2HX2u5SxgQQqslkJBHTJnreAniKZRa0nuv/gdo5yEXpmAvChXrqO5GZym9XUjgGjLCYC921FA5olxU/h9DzzQAZqfq/jAVTioYrS5EjrMaRSpf/kMEu3wasgXrekbgIkpQ6XJhdzadbcbmVpBuOwZSUsNHOX70IMJ6UfU0N/WylO3xiHmY6AHhe+bcAMH0ja+QoyVUljC635Oe6Is/lrfAi9oMTw2J+59sD2TY7jZj6H7eqY2fTmniXBH4aCfijtyO95OLV9BPgPgsXIS93VRGVD5a/pQtsMzkv1b9e1mI9mEPjfXpJR3BAmkrzi9WIbsI4Ga158XWaVYxsZ1OEQv5AjLZpjB3O88n0X+/kWQKgiWAWJZ21AfoUDwEiaQQw1wLFNbRg2IG4t780imj6LDc8/U26xjXaRZQYKk7rvRK2iaznCxhZ2Vvo+anvRjI/yfsRxgpERFBAMQCjOIU9am99ojR8UkAKw8CQT4j9+hsdTU/pd/EG9DM3L5+EZICO8vKNG5TTi3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
